version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    container_name: mytraining-api
    ports:
      - "3000:3000"
      - "9230:9229"
